baseURL: ""
languageCode: en-us
title: Dayoung's Devlog
theme: PaperMod

menu:
  main:
    - identifier: categories
      name: Categories
      url: /categories/
      weight: 10
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 20
    - identifier: archives
      name: Archives
      url: /archives/
      weight: 30

params:
  homeInfoParams:
    Title: "Welcome to my devlog"
    Content: "Frontend Devloper[![My Skills](https://skillicons.dev/icons?i=html,css,js,typescript,java,react,vue&theme=light)](https://skillicons.dev)"
  socialIcons:
    - name: email
      url: "https://mail.google.com/mail/?view=cm&fs=1&to=dayoungpyo@gmail.com&su=Subject%20Here&body=Body%20text%20here"
    - name: github
      url: "https://github.com/celestedayoung"
  ShowBreadCrumbs: true
  ShowSharButtons: true
  ShowPostNavLinks: true
